<#
.SYNOPSIS
    Write a Raspberry Pi OS first-boot config (custom.toml) to an already-flashed
    SD card's boot partition. Use this if the flasher wrote the image but could
    not write the config (e.g. Raspberry Pi Imager ejected the card after writing).

.DESCRIPTION
    Non-destructive: it only creates <BootDrive>:\custom.toml. It does not touch
    the rest of the card and needs no Administrator rights.

.PARAMETER BootDrive
    Drive letter of the boot partition (label "bootfs"). Auto-detected if omitted.

.PARAMETER LoginPassword
    Password for the Pi user. Prompted if omitted.

.EXAMPLE
    .\provision\write_boot_config.ps1 -WifiSsid "linksysr" -WifiPassword "4442221111" -LoginPassword "secret"
#>
param(
    [string]$BootDrive = "",
    [string]$Hostname = "nfc-jukebox",
    [string]$User = "pi",
    [string]$WifiSsid = "",
    [string]$WifiPassword = "",
    [string]$WifiCountry = "US",
    [string]$Timezone = "America/New_York",
    [string]$LoginPassword = ""
)

$ErrorActionPreference = "Stop"
function Info($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[OK] $m" -ForegroundColor Green }
function Die($m)  { Write-Host "[FAIL] $m" -ForegroundColor Red; exit 1 }

# --- Find the boot partition ---
if ($BootDrive -eq "") {
    $vol = Get-Volume -ErrorAction SilentlyContinue |
        Where-Object { $_.FileSystemLabel -eq "bootfs" -and $_.DriveLetter }
    if (-not $vol) {
        Die "Could not find a 'bootfs' partition. Re-insert the SD card and pass -BootDrive <letter>."
    }
    $BootDrive = "$($vol.DriveLetter)"
}
$BootDrive = $BootDrive.TrimEnd(':')
$bootRoot = "${BootDrive}:\"
if (-not (Test-Path (Join-Path $bootRoot "config.txt"))) {
    Die "${bootRoot} does not look like a Raspberry Pi OS boot partition (no config.txt)."
}
Ok "Boot partition: $bootRoot"

# --- openssl for password hashing ---
$openssl = (Get-Command openssl -ErrorAction SilentlyContinue).Source
if (-not $openssl) {
    foreach ($c in @("$env:ProgramFiles\Git\usr\bin\openssl.exe",
                     "${env:ProgramFiles(x86)}\Git\usr\bin\openssl.exe")) {
        if (Test-Path $c) { $openssl = $c; break }
    }
}
if (-not $openssl) { Die "openssl not found. Install Git for Windows (https://git-scm.com/download/win)." }

# --- SSH key (generate if missing) ---
$sshDir = Join-Path $env:USERPROFILE ".ssh"
$keyPub = Join-Path $sshDir "id_ed25519.pub"
if (-not (Test-Path $keyPub)) {
    Info "Generating SSH key (~/.ssh/id_ed25519)..."
    if (-not (Test-Path $sshDir)) { New-Item -ItemType Directory -Path $sshDir | Out-Null }
    & ssh-keygen -t ed25519 -f (Join-Path $sshDir "id_ed25519") -N '""' | Out-Null
}
$pubKey = (Get-Content $keyPub -Raw).Trim()
Ok "SSH public key ready"

# --- Password ---
if ($LoginPassword -eq "") {
    $sec = Read-Host "Set a login password for user '$User'" -AsSecureString
    $LoginPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
}
$pwHash = (& $openssl passwd -6 $LoginPassword).Trim()

# --- Wi-Fi (optional) ---
$wlanBlock = ""
if ($WifiSsid -ne "") {
@"
[wlan]
ssid = "$WifiSsid"
password = "$WifiPassword"
password_encrypted = false
country = "$WifiCountry"
hidden = false

"@ | Set-Variable -Name wlanBlock
}

$toml = @"
# Generated by write_boot_config.ps1 -- Raspberry Pi OS first-boot configuration.
[system]
hostname = "$Hostname"

[user]
name = "$User"
password = "$pwHash"
password_encrypted = true

[ssh]
enabled = true
password_authentication = true
authorized_keys = [ "$pubKey" ]

$wlanBlock[locale]
keymap = "us"
timezone = "$Timezone"
"@

$tomlPath = Join-Path $bootRoot "custom.toml"
$toml | Out-File -FilePath $tomlPath -Encoding ascii -NoNewline
Ok "Wrote $tomlPath"
Write-Host ""
Write-Host "Done. Eject the card, put it in the Pi, and power on." -ForegroundColor Green
Write-Host "Then: .\provision\finish_setup.ps1 -PiHost <ip> -User $User" -ForegroundColor Green
